# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c40e38c3bb8eaf323dae0b51964261bc"
application_url = "https://pni-mrpet-imageuploader.vercel.app"
embedded = true
name = "mr-pet-image-uploader"
handle = "mr-pet-image-uploader"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_files"

[app_proxy]
url = "https://pni-mrpet-imageuploader.vercel.app/api"
prefix = "apps"
subpath = "service-bridge"

[auth]
redirect_urls = [
  "https://pni-mrpet-imageuploader.vercel.app/auth/callback",
  "https://pni-mrpet-imageuploader.vercel.app/auth/shopify/callback",
  "https://pni-mrpet-imageuploader.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "mrpetdevelopment.myshopify.com"
automatically_update_urls_on_dev = true
